excluded:
  - Carthage
  - Pods
  - .build
  - Build
  - DerivedData

disabled_rules:
  - type_name
  - identifier_name
  - line_length
  - multiple_closures_with_trailing_closure

# force warnings
force_cast: warning
force_try: warning 