name: "TrafficRulesExam CI"

on: 
  push:
    branches: 
      - master
      - develop
      - hotfix
      - feature/stats
    paths:
      - TrafficRulesExam*
      - 'TrafficRulesExam/**'
      - '.github/workflows/**'

concurrency: 
  group: ci
  cancel-in-progress: true
jobs:
  macOS_5_4:
    name: Run tests (swift 5.5)
    runs-on: macOS-11
    env:
      DEVELOPER_DIR: /Applications/Xcode_13.2.app/Contents/Developer
    timeout-minutes: 10
    strategy:
      matrix:
        destination: ['OS=15.2,name=iPhone 12']
    steps:
      - uses: actions/checkout@v2
      - name: Build
        run: xcodebuild build-for-testing -project TrafficRulesExam.xcodeproj -scheme TrafficRulesExam -destination "${{ matrix.destination }}"
      - name: Test 
        run: xcodebuild test-without-building -project TrafficRulesExam.xcodeproj -scheme TrafficRulesExam -destination "${{ matrix.destination }}"
